name: 🎉 Release Binary

on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: "release --clean"
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"